language: node_js
node_js:
  - '10'
script:
  - npm install
before_deploy:
  - npm run build
deploy:
  provider: npm
  edge: true
  email: developer@dragonchain.com
  api_key:
    secure: gDghouhKI34AYBM7TvbFJRgp7WGZ6dY1Ndk0nSxjHBnwthGvjhZ6H9mXdSe3o2Z4lT37+AjKMMonbBA8NnsJX1qHAu+G0fnYgJeS8EVXzBUvwTZBTbyq5pCAVYiDjeSQElk0ArHts4lFki7HZKdd77cX8OuUyNxGxGhcovroaUuqPVGRv7m+xqjyNjE0b0BicmILdSSPgVlzpT0zeNfMecSmZhASJlIsi04jTcPbGqJQaG3dLy6Y0HvDDeiP2UA2DodYnJFKpHXYSAp+RK8+CZHaf0wnaM1aFgCbh7B0BwXk2PfUN6B3l42oCLoQHzIEAJHQUjjdTqFSJfegvXXYQ2R4QyR8aDwlq0T5UWAOwwpmdVb8MzfuMrCelaTl+KhmSZGLvVGZ06RexvBJpYCzPb/UZ4L8byvv+EVvcW+g4Hzct/mqjdPvKSBhP6fQoMIl4hVcvIjDDhqia7w54MZBbAiYHnWvMtkBxzc+BHBmJye9SmlAWIhnbmtHvLhJYx9aEUALPceKimGMqNeDIt3WWwOCkjAXhIy7Ku8fGOJv7SL4nO3h9N9u4OVgGMGC3cguFMAEr3N34RNY2RMHTMKaKCj/4gF7PCVYakCiXB/Fsy0vYTzgJEmxjmO+R/Q51QUnjNC949sCf7hh2OJCUVv0e+h6PxdDMbNMspKJQpQw8EA=
  on:
    repo: dragonchain/single-sign-on-component
    branch: master